---
default_set: 'windows_2008r2'
sets:
  'windows_2008r2':
    nodes:
      'windows-2008r2':
        prefab: 'windows_2008r2'
        options:
          gui: true
          ip: 10.0.2.15
  'windows_2012':
    nodes:
      'windows-2012':
        prefab: 'windows_2012'
        options:
          gui: true
          ip: 10.0.2.15